server:
  port: 8003


mybatis:
  type-aliases-package: com.wjh.pojo
  mapper-locations: classpath*:mybatis/mapper/*.xml


spring:
  application:
    name: springcloud-provide-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tencent:3306/springcloud2
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud-provide-dept8003

info:
  app.name: springcloud
  company.name: www.wjh.com
